name: Test Pysteps

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [ main ]


jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.10", "3.12"]
      max-parallel: 6

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Install pysteps on MacOS
        if: matrix.os == 'macos-latest'
        working-directory: ${{github.workspace}}
        env:
          CC: gcc-13
          CXX: g++-13
          CXX1X: g++-13
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew update-reset
          brew update
          gcc-13 --version || brew install gcc@13
          pip install git+https://github.com/pySTEPS/pysteps@postprocessor_plugin
          python -c "import pysteps"

      - name: Install pysteps on Windows and Linux
        if: matrix.os != 'macos-latest'
        run: |
          pip install git+https://github.com/pySTEPS/pysteps@postprocessor_plugin
          python -c "import pysteps"

      - name: Run tests
        run: pytest -x

