name: Test Pysteps

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.6", "3.8" ]
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies for MacOS
        if: matrix.os == 'macos-latest'
        working-directory: ${{github.workspace}}
        env:
          CC: gcc-9
          CXX: g++-9
          CXX1X: g++-9
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew update-reset
          brew update
          brew install gcc@9
          gcc-9 --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip -r{toxinidir}/requirements_dev.txt
          pip install git+https://github.com/pySTEPS/pysteps@importer_plugins_support
          python -c "import pysteps"

      - name: Run tests
        run: pytest -x

