name: Test Pysteps

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [ main ]


jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        # Note: The python versions were changed due to the latest versions of ubuntu and windows no longer having support for python 3.6 or 3.8.
        # Note: MacOS compatibility has been removed due to no gcc compatibility with the latest versions of MacOS.
        python-version: [ "3.9", "3.11"]
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

#      - name: Install pysteps on MacOS
#        if: matrix.os == 'macos-latest'
#        working-directory: ${{github.workspace}}
#        env:
#          CC: gcc-9
#          CXX: g++-9
#          CXX1X: g++-9
#          HOMEBREW_NO_INSTALL_CLEANUP: 1
#        run: |
#          brew update-reset
#          brew update
#          brew install gcc@9
#          gcc-9 --version
#          pip install git+https://github.com/pySTEPS/pysteps
#          python -c "import pysteps"

      - name: Install pysteps on Windows and Linux
        if: matrix.os != 'macos-latest'
        run: |
          pip install git+https://github.com/pySTEPS/pysteps
          python -c "import pysteps"

      - name: Run tests
        run: pytest -x

